# Configuration https://fly.io/docs/reference/configuration/

app = 'iot-spotify-api'
primary_region = 'waw'

[build]
  [build.args]
    GO_VERSION = '1.22.3'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
